name: Upload Test Coverage Report

inputs:
  filename:
    description: "The filename for an xcresult file."
    required: true
    type: string
  scheme_name:
    description: "The name for the scheme."
    required: true
    type: string
  token:
    description: "The token for uploading to CodeCov."
    required: true
    type: string
  output_path:
    description: "The output code coverage report path."
    required: true
    type: string
    default: test_output

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        brew tap a7ex/homebrew-formulae
        brew install xcresultparser
      shell: bash

    - name: Convert the test report
      run: |
        xcresultparser -o cobertura "test_output/${{ inputs.filename }}.xcresult" > cobertura.xml
      shell: bash
  
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5.1.2
      with:
        token: ${{ inputs.token }}
        flags: ${{ inputs.scheme_name }}
        fail_ci_if_error: true
        verbose: true
        files: ./cobertura.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.filename }}
        path: ${{ inputs.output_path }}
